name: Request Assignment Repository
description: Instantly provision your private assignment repository using your official student email address.
title: "Private Repository Request"
labels: ["provision-repo"]
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to the PG2 Course!
        Clicking submit below will automatically create your personal repository under our organization.
  - type: input
    id: student_email
    attributes:
      label: University Email Address
      placeholder: Enter your Full Sail student email address.
    validations:
      required: true
